version: '3.9'

services:
  web:
    build:
      context: .
    container_name: django_app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DEBUG=1
    env_file:
      - .env  # Reference to your .env file

  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: scrumflow
    ports:
      - "5433:5432" # Map host port 5433 to container port 5432